#include "whisper_turbo_q8.h"
#define WHISPER_TURBO_HAVE_DECODER_Q8_DOT 1
#define whisper_turbo_decoder_q8_dot wt_q8_row_auto
#define WHISPER_TURBO_HAVE_DECODER_Q8_GEMM 1
#define whisper_turbo_decoder_q8_gemm wt_decoder_q8_gemm
